name: System Maintenance

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  maintenance:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install browser
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
        
    - name: Install packages
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        
    - name: Prepare resources
      env:
        TASK_CONFIG: ${{ secrets.TASK_CONFIG }}
        SDK_INFO: ${{ secrets.SDK_INFO }}
      run: |
        echo "$TASK_CONFIG" > config.py
        echo "$SDK_INFO" > sdk.json
        
    - name: Execute task
      run: |
        python config.py
        
    - name: Cleanup
      if: always()
      run: |
        rm -f config.py
        rm -f sdk.json
